### PR TITLE
make Ansible adapter to dump each host variables in '--list' mode

### PR DESCRIPTION
**Pull request by sa2ajj**
- the feature was introduced in Ansible 1.3
- to keep the old behaviour an option '--pre-1.3' is added to the
  adapter

I am not sure if this patch is up to your standards, so I'd be more than happy to accomodate any changes you'd see fit.

### CODE REVIEW

**Comment by mcqueenorama** [comment]
This looks like its been approved.  How about merging this thing?  I know the ansible subject is a bit controversial, but how about getting this merged?

**Comment by jcftang** [comment]
+1 for merging this

**Comment by madduck** [comment]
also sprach Jimmy Tang <notifications@github.com> [2016-03-20 14:39 +0100]:
> +1 for merging this

Sorry guys for having been an absolute nightmare upstream. I really
hope to have some time and energy in the near future.

-- 
The sender e-mail address used (reply.github.com@pobox.madduck.net)
is valid and specific to our correspondence. It should not indicate any
affiliation with your organisation.
 
Die verwendete E-mail-Adresse (reply.github.com@pobox.madduck.net)
ist gültig und spezifisch für unsere Korrespondenz. Sie soll in keiner Weise
auf eine Verbindung mit Ihrer Organisation hindeuten.
 
Spamtrap: reply.github.com.bogus@pobox.madduck.net

**Comment by Cerebus** [comment]
This PR isn't strictly necessary for ansible, but contrary to ansible's script convention Ansible Tower doesn't invoke the inventory script with '--host' when the _meta key is absent, so host_vars from reclass never get ingested.

**Comment by sa2ajj** [comment]
I'm not sure what is going to happen to this PR...

**Pull request closed without merging**
