### PR TITLE
do not escape the key string when creating a subpath

### PR DESCRIPTION
**Pull request by dvandok**
Please review this minor change; for me it fixes issue #64.

### CODE REVIEW

**Comment by lottspot** [comment]
I would rather not remove a code path which we know was written in for a reason (even if we aren't yet sure what that reason is). We should take a harder look at this problem and see if there's some way for us to solve it that doesn't involve the elimination of a code path, or at the very least, provides an alternate solution to the problem the code path was introduced to solve to begin with.

**Comment by dvandok** [comment]
I understand your point of view, but this fits the 'lava flow' pattern. The patch I put forward is a bit provocative, but consider it a challenge; to find a counter-example (i.e. some use case that is broken by this change) or admit it's safe and sound. I don't know enough about the intricacies of Python or this code base to be sure either way.

**Comment by Rtzq0** [comment]
Hello @dvandok. I agree with @lottspot on this. Removal/alteration of existing code paths needs to come with a **strong** assertion as to why this is the correct approach. This needs to come along with the patch, not be left to the reviewer. @lottspot has done the same to me previously, and he was justified in doing so.

Remember that as an ENC reclass is a platform upon which other platforms are built. Our testing is admittedly weak and therefore we **must** err on the side of caution with regard to improvements rather thank risking potential breakage of existing deployments.

**Comment by dvandok** [comment]
OK, looking at the code of dictpath.py it is clear that the escaping of the key should be countered by the _unescaping_ at some other point, but this never happens. So any occasion of having a delimiter as part of the key will result in errors. The escaping is not required as the data is stored in arrays, not strings; the delimiter is only needed when creating a DictPath from a string. When outputting the string rep of the DictPath the escaped delimiter is a visual aid at best, so the ```__str__``` function should probably use an escape function instead.
What I don't understand about the original code is the ```try...except AttributeError```. Probably only @madduck can explain that.

I understand the caution but the class is not that complicated. It's broken now if you try to specify IPv6 addresses as keys in reclass (my very real use case).

Logically, any existing deployment that has the delimiter in any of its keys is already broken, and any existing deployment that doesn't have the delimiter in any of its keys should be completely unaffected by this change, because it only skips the escaping of delimiters in any of the keys.

**Pull request closed without merging**
