### PR TITLE
doc for use reclass directly from Python

### PR DESCRIPTION
**Pull request by michaelkuty**

### CODE REVIEW

**Comment by jcftang** [comment]
+1

**Comment by Rtzq0** [comment]
@lottspot it looks like this may be something folks are interested in. Do you see anything problematic in here blocking a merge?

**Comment by michaelkuty** [comment]
Yes, This branch needs cleanup because remote FS is another issue, yaml extension not works.

**Comment by Rtzq0** [comment]
@michaelkuty thanks for your response, please let me know **_explicitly_** if you have an intention to perform this work. Otherwise I'll close this out, create a branch off of 0c3291654 and submit a fresh PR for that.

**Comment by michaelkuty** [comment]
Yes, please close this and make fresh one :)

**Comment by Rtzq0** [comment]
Thanks for clarifying so promptly :-)

**Pull request closed without merging**
