### PR TITLE
Support escaping of interpolation sequences in RefValue strings

### PR DESCRIPTION
**Pull request by ppmathis**
RefValue string interpolation is now being done with a simplified lexer/parser and supports escaping, to avoid unwanted string interpolation. The new string interpolation mechanism does not break backwards compatibility (except [escape sequence][interpolation sequence], which will now be solely printed as [interpolation sequence]) to the existing solution, by falling back to a literal escape character when there is nothing to escape.

This pull request is meant to close issue #55, which requested the ability to escape string interpolation sequences. The new escape character, which is defined as a backslash ('\\') per default, could also be used as an escape character for the application list, to solve issue #63 - but this should be probably put into a separate PR.

Happy to accept all kinds of feedback - tried to keep the code clean by eliminating all PyLint errors in the RefValue module, except the one stating that there is no module docstring (as this project does not seem to have them anywhere either). Also added some tests for backwards compatibility and the escaping feature itself.

### CODE REVIEW

**Comment by lottspot** [comment]
We discussed this a bit in the issue thread, but I prefer this solution to the problem and would like to see this PR merged. I'll give @Rtzq0 a couple days to take a look at this and provide feedback if he has any. Otherwise, we'll move forward with merging this.

**Comment by Rtzq0** [comment]
I think this looks good but I haven't had a chance to test it yet. @lottspot have you performed any testing?

If not I'd say provisionally yes I'm all for it and this looks great, but I'd like to wait until i get home to check out this branch.

**Comment by NeoXiD** [comment]
No idea how many active reclass users are watching this repository but getting as many testers as possible would be definitely great. For me it works just fine, covering dozens of nested variables and such for SaltStack, but maybe it would break somewhere else or there might still be a rare edge case.

I tried to cover all situations that came into my mind - but there's always that one user doing something real special :)

**Comment by ppmathis** [comment]
As I am no longer using reclass and this pull request did not seem to move on for more than a year, I decided to close it by myself unmerged. If anyone is interested in taking over or taking snippets/parts of my solution, feel free to do so.

**Pull request closed without merging**
